import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Rotas dinâmicas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Link href="/">Home</Link>
        <Link href="/produtos">Produtos</Link>
        {children}
      </body>
    </html>
  );
}
